services:
  airflow-webserver:
    image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.6.3}
    networks:
      - app-network
      - astro_default
    depends_on:
      - mysql  # Use o nome do serviço, não do container

  airflow-scheduler:
    image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.6.3}
    networks:
      - app-network
      - astro_default
    depends_on:
      - mysql

networks:
  app-network:
    external: true
  astro_default:
    external: true