services:
  mysql:
    image: mysql:8.0
    container_name: mysql8
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: pipelinestreaming
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
      MYSQL_ROOT_HOST: '%'
    command: --local-infile=1 --secure-file-priv=""
    volumes:
      - mysql_data:/var/lib/mysql
      - sql_scripts:/sqlfiles
      - ./data:/arquivos_csv

    networks:
      - app-network

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8090:8080" # porta alterada para 8090 para evitar conflitos com Airflow
    networks:
      - app-network

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Console
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - app-network

  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - HOME=/tmp
    ports:
      - "7077:7077"
      - "8081:8080"  # Spark UI
    volumes:
      - ./spark:/scripts
    depends_on:
      - minio
      - mysql
    networks:
      - app-network

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - HOME=/tmp
    depends_on:
      - spark-master
    volumes:
      - ./spark:/scripts
    networks:
      - app-network

volumes:
  mysql_data: {}
  arquivos_csv:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
  sql_scripts:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./scripts
  minio_data: {}

networks:
  app-network:
    driver: bridge
    name: app-network