# mkdocs.yml
site_name: Streaming de vídeos - Pipeline Completo
site_description: Documentação de projeto ABP - UNISATC
site_author: Bruno, João Gabriel, João Pedro, Rafael e Yasmin
site_url: https://meusite.github.io/

# Repository
repo_name: brunogmadeira/ABP-eng-de-dados
repo_url: https://github.com/brunogmadeira/ABP-eng-de-dados.git

# Configuration
theme:
  name: material
  language: pt
  palette:
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Modo claro
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Modo escuro
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - content.code.copy

# Navigation
nav:
  - Home: index.md
  - Configuração do Ambiente: config-ambiente.md
 

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - admonition
  - pymdownx.details
  - attr_list
  - toc:
      permalink: true

# Plugins
plugins:
  - search:
      lang: pt