SET FOREIGN_KEY_CHECKS = 0;

LOAD DATA INFILE '/arquivos_csv/planos.csv'
INTO TABLE planos
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;

LOAD DATA INFILE '/arquivos_csv/usuarios.csv'
INTO TABLE usuarios
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;

LOAD DATA INFILE '/arquivos_csv/dispositivos.csv'
INTO TABLE dispositivos
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;

LOAD DATA INFILE '/arquivos_csv/generos.csv'
INTO TABLE generos
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;

LOAD DATA INFILE '/arquivos_csv/videos.csv'
INTO TABLE videos
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;

LOAD DATA INFILE '/arquivos_csv/pagamentos.csv'
INTO TABLE pagamentos
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;

LOAD DATA INFILE '/arquivos_csv/cancelamentos.csv'
INTO TABLE cancelamentos
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;

LOAD DATA INFILE '/arquivos_csv/eventos.csv'
INTO TABLE eventos
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;

LOAD DATA INFILE '/arquivos_csv/favoritos.csv'
INTO TABLE favoritos
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;

LOAD DATA INFILE '/arquivos_csv/avaliacoes.csv'
INTO TABLE avaliacoes
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;

LOAD DATA INFILE '/arquivos_csv/visualizacoes.csv'
INTO TABLE visualizacoes
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 ROWS;

SET FOREIGN_KEY_CHECKS = 1;
